spring:
  application:
    name: RECRUITMENT-APP
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: master
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/company-management
    username: postgres
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8777/eureka/
am-service-url: http://ACCESS-MANAGEMENT/api